name: Publish SDK Demos

on:
  workflow_run:
    workflows:
      - 'Tag Demos Release'
    types:
      - completed

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@upstreampay'

      - name: Install dependencies
        working-directory: sandpack
        run: npm install

      - name: Build
        working-directory: sandpack
        run: npm run build
        env:
          VITE_PURSE_SESSION_URL: https://usp-widget-merchant.purse-sandbox.com/orchestration_session/
          VITE_PURSE_ORDER_URL: https://usp-widget-merchant.purse-sandbox.com/orchestration_order/

      - name: Publish
        working-directory: sandpack
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
