name: Demos Release

on:
  push:
    branches:
      - main
    paths:
      - 'sandpack/**'

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEMOS_ADMIN_ACCES_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: sandpack
        run: npm install

      - name: Release
        working-directory: sandpack
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEMOS_ADMIN_ACCES_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
